"use client";

import { useVertical } from "@/components/VerticalContext";

/**
 * FloorLedger — one object, two states, carrying the page's central argument
 * across two sections.
 *
 * #problem says a signal exists in the room and goes unrecorded. #value says
 * you can now answer questions about it. Those are the same sentence read
 * forwards and backwards, so they get the SAME instrument rather than two
 * unrelated illustrations: a day in the venue, one track per zone.
 *
 *   mode="blind"     one track carries data (the door), the rest are empty
 *                    rails marked unrecorded. This is the whole of what a
 *                    ticketing or turnstile system holds.
 *   mode="measured"  every track carries the day, minute by minute, and the
 *                    peak on each one is marked.
 *
 * A reader who has scrolled past #problem meets the identical geometry at
 * #value with the blanks filled in, which is an argument a paragraph cannot
 * make. It is also why this is not the venue plan from #venue: the plan
 * answers "where", and the thing #problem is missing is "when, and for how
 * long".
 *
 * HONESTY (§9, §4d rule 2). Nothing here came from a venue. The profiles are
 * generated by the deterministic shaper below from a hand-set peak hour and
 * weight per zone, and every panel carries an "Illustrative" chip. Deterministic
 * matters twice over: Math.random() would differ between the server render and
 * the client one, and the capture harness needs the same bytes twice.
 *
 * COLOUR. A nested product-register stage inside the canvas-register section,
 * exactly as the Outputs beats are, so the instrument scale is on-stage white
 * in all four palettes.
 *
 * MOTION. Static geometry computed at module scope. Nothing to freeze.
 */

const W = 480;
const H = 216;
/** Left gutter: zone names sit here, tracks start after it. */
const GUT = 116;
const X0 = GUT + 4;
const X1 = W - 14;
const ROW_H = 31;
const TOP = 30;
const BARS = 40;

type Track = {
  name: string;
  /** Where this zone's day peaks, 0..1 across opening hours. */
  peak: number;
  /** How busy it gets at all, 0..1. */
  weight: number;
  /** Second, smaller bump — a lunchtime or an evening class. */
  second?: number;
};

type Venue = {
  door: Track;
  zones: Track[];
  hours: string[];
  /** What the operator's existing system is called. */
  source: string;
};

const MUSEUM: Venue = {
  door: { name: "Entrance", peak: 0.34, weight: 1 },
  zones: [
    { name: "Renaissance", peak: 0.42, weight: 0.88, second: 0.78 },
    { name: "Impressionists", peak: 0.56, weight: 0.72 },
    { name: "Dutch Masters", peak: 0.3, weight: 0.54, second: 0.66 },
    { name: "Modern Wing", peak: 0.72, weight: 0.61 },
  ],
  hours: ["10:00", "12:00", "14:00", "16:00", "18:00"],
  source: "ticketing",
};

const GYM: Venue = {
  door: { name: "Turnstile", peak: 0.78, weight: 1, second: 0.16 },
  zones: [
    { name: "Cardio", peak: 0.8, weight: 0.9, second: 0.18 },
    { name: "Free weights", peak: 0.84, weight: 0.82 },
    { name: "Studio", peak: 0.62, weight: 0.48, second: 0.2 },
    { name: "Strength", peak: 0.76, weight: 0.66 },
  ],
  hours: ["06:00", "10:00", "14:00", "18:00", "22:00"],
  source: "turnstile",
};

/**
 * A day, as BARS samples in 0..1. Two gaussians plus a fixed jitter: the
 * jitter is what stops five tracks reading as five copies of one curve, and
 * it is a hash of (index, seed) rather than a random so the render is stable.
 */
function profile(t: Track, seed: number): number[] {
  const bump = (x: number, c: number, s: number) => Math.exp(-((x - c) ** 2) / (2 * s * s));
  return Array.from({ length: BARS }, (_, i) => {
    const x = i / (BARS - 1);
    const h = Math.sin((i + 1) * 12.9898 + seed * 78.233) * 43758.5453;
    const jitter = 0.82 + 0.36 * (h - Math.floor(h));
    // s=0.11 rather than a wider bell: at 0.15 four tracks with different peak
    // hours still overlapped enough to read as four copies of one curve, which
    // defeats the whole point of showing the floor room by room.
    const v =
      bump(x, t.peak, 0.11) + (t.second !== undefined ? 0.6 * bump(x, t.second, 0.08) : 0);
    return Math.max(0.04, Math.min(1, v * t.weight * jitter));
  });
}

const BAR_W = (X1 - X0) / BARS;

function Bars({ values, y, strong }: { values: number[]; y: number; strong: boolean }) {
  const base = y + ROW_H - 6;
  const span = ROW_H - 10;
  return (
    <g fill={strong ? "var(--instrument-fg-strong)" : "var(--instrument-fg-weak)"}>
      {values.map((v, i) => (
        <rect
          key={i}
          x={X0 + i * BAR_W}
          y={base - v * span}
          width={BAR_W - 1.6}
          height={Math.max(1, v * span)}
          opacity={0.32 + 0.68 * v}
        />
      ))}
    </g>
  );
}

export default function FloorLedger({ mode }: { mode: "blind" | "measured" }) {
  const { vertical } = useVertical();
  const v = vertical === "gyms" ? GYM : MUSEUM;
  const measured = mode === "measured";
  const doorValues = profile(v.door, 1);

  return (
    <div
      data-register="product"
      className="relative aspect-[16/9] w-full overflow-hidden rounded-xl border border-line-card sm:aspect-[480/216]"
    >
      <svg
        viewBox={`0 0 ${W} ${H}`}
        preserveAspectRatio="xMidYMid meet"
        className="absolute inset-0 h-full w-full"
        aria-hidden="true"
        focusable="false"
      >
        <g fontFamily="var(--font-mono)" fontSize="9" letterSpacing="0.4">
          {/* The door track. It is the one line both states share, which is
              what makes the two panels legible as the same day. */}
          <g>
            <text x="10" y={TOP + 13} fill="var(--instrument-fg-strong)">
              {v.door.name}
            </text>
            <text x="10" y={TOP + 24} fill="var(--instrument-fg)" opacity="0.7" fontSize="8">
              {v.source}
            </text>
            <Bars values={doorValues} y={TOP} strong />
          </g>
          <line
            x1="10"
            y1={TOP + ROW_H - 3}
            x2={X1}
            y2={TOP + ROW_H - 3}
            stroke="var(--instrument-fg-faint)"
            strokeWidth="0.6"
          />

          {v.zones.map((z, i) => {
            const y = TOP + ROW_H + i * ROW_H;
            const values = profile(z, i + 2);
            const peakIndex = values.indexOf(Math.max(...values));
            return (
              <g key={z.name}>
                <text
                  x="10"
                  y={y + 15}
                  fill={measured ? "var(--instrument-fg-strong)" : "var(--instrument-fg)"}
                  opacity={measured ? 1 : 0.6}
                >
                  {z.name}
                </text>
                {measured ? (
                  <>
                    <Bars values={values} y={y} strong={false} />
                    {/* The peak, marked with the same square handle the venue
                        plan uses for a camera: this is the hour the zone made. */}
                    <rect
                      x={X0 + peakIndex * BAR_W + BAR_W / 2 - 2.5}
                      y={y + ROW_H - 6 - values[peakIndex] * (ROW_H - 10) - 7}
                      width="5"
                      height="5"
                      fill="var(--instrument-fg-strong)"
                    />
                  </>
                ) : (
                  <>
                    {/* An empty rail, not an empty space: the track exists,
                        and nothing is written on it. */}
                    <line
                      x1={X0}
                      y1={y + ROW_H - 6}
                      x2={X1}
                      y2={y + ROW_H - 6}
                      stroke="var(--instrument-fg-faint)"
                      strokeWidth="0.8"
                      strokeDasharray="2 5"
                    />
                    <text
                      x={X1}
                      y={y + ROW_H - 9}
                      textAnchor="end"
                      fill="var(--instrument-fg)"
                      opacity="0.6"
                      fontSize="8"
                    >
                      unrecorded
                    </text>
                  </>
                )}
              </g>
            );
          })}

          {/* Hour axis. */}
          <line
            x1={X0}
            y1={H - 18}
            x2={X1}
            y2={H - 18}
            stroke="var(--instrument-fg-faint)"
            strokeWidth="0.6"
          />
          {v.hours.map((h, i) => {
            const x = X0 + ((X1 - X0) * i) / (v.hours.length - 1);
            return (
              <g key={h}>
                <line
                  x1={x}
                  y1={H - 18}
                  x2={x}
                  y2={H - 14}
                  stroke="var(--instrument-fg-faint)"
                  strokeWidth="0.6"
                />
                <text
                  x={x}
                  y={H - 5}
                  textAnchor={i === 0 ? "start" : i === v.hours.length - 1 ? "end" : "middle"}
                  fill="var(--instrument-fg)"
                  opacity="0.7"
                  fontSize="8"
                >
                  {h}
                </text>
              </g>
            );
          })}
        </g>
      </svg>

      <div className="absolute left-3 right-3 top-2.5 flex items-baseline justify-between gap-2 sm:left-4 sm:right-4 sm:top-3">
        <span className="truncate text-[11px] font-medium text-instrument-fg-strong sm:text-xs">
          {measured ? "The same day, measured" : "One day, as you have it today"}
        </span>
        <span className="shrink-0 rounded-full border border-line-hairline px-1.5 py-0.5 font-mono text-[9px] text-instrument-fg">
          Illustrative
        </span>
      </div>

      <p className="sr-only">
        {measured
          ? `Illustration: a day in a synthetic ${vertical === "gyms" ? "club" : "gallery"}, one track per zone, every track carrying activity minute by minute with its busiest moment marked.`
          : `Illustration: the same day, with only the ${v.door.name.toLowerCase()} track carrying data and every zone track empty and marked unrecorded.`}
      </p>
    </div>
  );
}
